services:
  n8n:
    build: .
    image: n8n-custom:1.97.1
    environment:
      GENAI_PYTHON_PACKAGES: "opencv-python-headless numpy Pillow moviepy"
      N8N_RUNNERS_ENABLED: "true"
      N8N_HOST: "https://paintaisystemn8n.ggff.net/"
      N8N_EDITOR_BASE_URL: "https://paintaisystemn8n.ggff.net/"
      WEBHOOK_URL: "https://paintaisystemn8n.ggff.net/"
      GENERIC_TIMEZONE: "Asia/Bangkok"
      TZ: "Asia/Bangkok"
      DB_TYPE: "postgresdb"
      DB_POSTGRESDB_DATABASE: "n8n"
      DB_POSTGRESDB_HOST: "postgresql"
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: "n8n_user"
      DB_POSTGRESDB_SCHEMA: "public"
      DB_POSTGRESDB_PASSWORD: "your_secure_password_here"
    volumes:
      - n8n-data:/home/node/.n8n
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:5678/'
      interval: 5s
      timeout: 20s
      retries: 10
    ports:
      - "5678:5678"

  postgresql:
    image: 'postgres:16-alpine'
    volumes:
      - 'postgresql-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=n8n_user
      - POSTGRES_PASSWORD=your_secure_password_here
      - POSTGRES_DB=n8n
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U n8n_user -d n8n'
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  n8n-data:
  postgresql-data:
